server:
  ip: 0.0.0.0
  port: 8090
  runmode: "debug"
  root: ""
  scheme: "https"
  dsn: "www.baidu.com"
  sslcert: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\certs\\server.crt"
  sslkey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\certs\\server.key"
  license: |
    eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVycyI6LTEsImVuZCI6IjIwMjYtMDEtMDMgMTA6Mjg6MDYiLCJwcm9kdWN0IjoiQ29uc29sZVNlcnZlciIsInNuIjoiMDAwMDAwMDAtMDAwMC
    0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwic3RhcnQiOiIyMDI1LTEyLTA0IDEwOjI4OjA2In0.nlKFfK-hCpd7dxgF8sZVMpnTqq6TXSWGXwmZtz6gs3s4DJqHANGJ5skiTg_evJXgyc53KpdbR0tYkQlFD
    wPZKg
#  usedb: false

logs:
  level: debug
  common:
    path: "logs"
    file: "rest-server.log"
    errorfile: "error.log"
    backups:
    - maxsize: 500
      maxbackups: 30
      maxage: 7
      localtime: true
      compress: true
      queuesize: 2048
    - maxsize: 50
      maxbackups: 30
      maxage: 30
      localtime: true
      compress: true
      queuesize: 1024
  access:
    path: "logs/access"
    file: "info.log"
    errorfile: "error.log"
    backups:
      - maxsize: 500
        maxbackups: 30
        maxage: 7
        localtime: true
        compress: true
        queuesize: 4096
      - maxsize: 50
        maxbackups: 30
        maxage: 30
        localtime: true
        compress: true
        queuesize: 512

database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: 123
  db: rest-server
  charset: utf8mb4
  loglevel: info

  # only mysql
  parsetime: True
  local: True

  # only postgres
  sslmode: verify-ca
  timezone: Asia/Shanghai
  sslrootcert: /etc/ssl/certs/ca-certificates.crt
  sslcert: /path/to/client.crt
  sslkey: /path/to/client.key

  # only sqlite
  cached: shared

auth:
  type: ecdsa
  lifetime: 864000
  privatekey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\private.pem"
  publickey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\public.pem"