server:
  ip: 0.0.0.0
  port: 8090
  runmode: "debug"
  usedb: false
  root: ""
  scheme: "http"
  sslcert: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\certs\\server.crt"
  sslkey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\certs\\server.key"
  license: |
    eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVycyI6LTEsImVuZCI6IjIwMjUtMTItMjY
    gMTA6NDM6MTkiLCJwcm9kdWN0IjoiQ29uc29sZVNlcnZlciIsInNuIjoiMTIzNDU2NzgiLCJzdGFydCI
    6IjIwMjUtMTEtMjYgMTA6NDM6MTkifQ.iKrdThEEBKpX9BkIsZ5iFzbXis4qwuxUBpj9Y_DBSD0xnvnG
    0dAeSRBxl57r983m4JKzj7Qg9St9dnczosDqDQ

logs:
  level: debug
  common:
    path: "logs"
    file: "rest-server.log"
    errorfile: "error.log"
    backups:
    - maxsize: 1
      maxbackups: 30
      maxage: 7
      localtime: true
      compress: true
      queuesize: 2048
    - maxsize: 50
      maxbackups: 30
      maxage: 30
      localtime: true
      compress: true
      queuesize: 1024
  access:
    path: "logs/access"
    file: "info.log"
    errorfile: "error.log"
    backups:
      - maxsize: 500
        maxbackups: 30
        maxage: 7
        localtime: true
        compress: true
        queuesize: 4096
      - maxsize: 50
        maxbackups: 30
        maxage: 30
        localtime: true
        compress: true
        queuesize: 512

auth:
  type: ecdsa
  regenerate: false
  privatekey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\private.pem"
  publickey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\public.pem"

keystone:
  endpoint: "http://192.168.231.108:5000/v3"
  domainname: "Default"
#  projectname: "admin"
  projectid: 8fccfb24481440088ac89091c876bae5
  region: RegionOne

