server:
  ip: 0.0.0.0
  port: 8080
  runmode: debug
logs:
  level: debug
  common:
    path: "logs"
    file: "rest-server.log"
    errorfile: "error.log"
    backups:
      - maxsize: 500
        maxbackups: 30
        maxage: 7
        localtime: true
        compress: true
        queuesize: 2048
      - maxsize: 50
        maxbackups: 30
        maxage: 30
        localtime: true
        compress: true
        queuesize: 1024
  access:
    path: "logs/access"
    file: "info.log"
    errorfile: "error.log"
    backups:
      - maxsize: 500
        maxbackups: 30
        maxage: 7
        localtime: true
        compress: true
        queuesize: 4096
      - maxsize: 50
        maxbackups: 30
        maxage: 30
        localtime: true
        compress: true
        queuesize: 512
database:
  user: root
  password: 123
  db: rest-server
  charset: utf8mb4
  parsetime: True
  local: True
  loglevel: error
auth:
  lifetime: 864000
  privatekey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\pri.key"
  publickey: "D:\\workspaces\\go\\src\\github.com\\yi-cloud\\rest-server\\etc\\rest-server\\auth\\pub.key"